#!/usr/bin/env python3
"""Generate Umbrel's native template without changing the accepted OS recipe.

Umbrel renders top-level *.template files and updates hooks on app upgrades.
5tratumOS consumes docker-compose.yml directly and preserves seeded data.
Keep the accepted initializer as the common source for migration/config logic.
"""
import argparse
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "willitmod-dev-bc2"


def artifacts():
    compose = yaml.safe_load((APP / "docker-compose.yml").read_text())
    init = (APP / "data/init/init.sh").read_text()
    start = init.index("# This check deliberately precedes every write")
    end = init.index("\natomic_json_write()", start)
    # This entrypoint is selected only by Umbrel's native template path. The
    # default 5tratumOS initializer and its OS version check remain untouched.
    init = init[:start] + (
        '# Umbrel owns the app lifecycle; the Core 31 migration checks below\n'
        '# are app-owned and remain mandatory on this platform.\n'
        '[ "${AXEBC2_PLATFORM:-}" = "umbrel" ] || fail "Umbrel entrypoint requires the Umbrel recipe"\n'
    ) + init[end:]
    init = init.replace(
        "# Normal initialization starts only after the OS floor and migration policy exist.",
        "# Normal initialization starts only after the migration policy exists.",
    )
    init = init.replace(
        'build_file="${AXEBC2_BUILD_FILE:-/etc/5tratumos/build.json}"\n', ""
    )
    generated = "# Generated by scripts/build-axebc2-umbrel.py; do not edit.\n"
    init = init.replace("#!/bin/sh\n", "#!/bin/sh\n" + generated, 1)
    services = compose["services"]
    svc = services["init"]
    svc["volumes"] = [v for v in svc["volumes"] if v["target"] != "/etc/5tratumos/build.json"]
    for volume in svc["volumes"]:
        if volume["target"] == "/opt/axebc2/init.sh":
            volume["source"] = "${APP_DATA_DIR}/hooks/umbrel-init"
    svc["environment"]["AXEBC2_PLATFORM"] = "umbrel"
    svc["command"] = ["/bin/sh", "/opt/axebc2/init.sh"]
    # No shell program is embedded in an envsubst template: unexported local
    # variables would otherwise disappear before Docker sees the command.
    pool = services["ckpool"]
    pool_script = "#!/bin/sh\n" + generated + pool["entrypoint"][-1].replace("$$ARGS", "$ARGS") + "\n"
    pool["entrypoint"] = ["/bin/sh", "/opt/axebc2/ckpool-entrypoint.sh"]
    pool["volumes"].append({
        "type": "bind", "source": "${APP_DATA_DIR}/hooks/umbrel-ckpool",
        "target": "/opt/axebc2/ckpool-entrypoint.sh", "read_only": True,
        "bind": {"create_host_path": False},
    })
    return {
        APP / "docker-compose.yml.template": generated + yaml.safe_dump(compose, sort_keys=False),
        APP / "hooks/umbrel-init": init,
        APP / "hooks/umbrel-ckpool": pool_script,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, text in artifacts().items():
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise SystemExit(f"Outdated generated Umbrel artifact: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            # These are container entrypoints, not executable host hooks.
            path.chmod(0o644)


if __name__ == "__main__":
    main()
